### ISSUE TITLE
成功配置，start后，自动断开，怎么查看是否开启成功?

### ISSUE THREAD

**Issue by androidcn** [ifyour/Hosts-for-Surge#2]
成功配置，start后，自动断开，怎么查看是否开启成功?

**Comment by ifyour** [comment]
@androidcn 顶部显示`VPN`字样表示开启成功。

**Comment by androidcn** [comment]
我知道，但是自动断开了，
我自己的配置没问题
我是最新的TestFlight版本
On Thu, Apr 14, 2016 at 5:36 PM Willard Wang <notifications@github.com>
wrote:

> @androidcn <https://github.com/androidcn> 顶部显示VPN字样表示开启成功。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ifyour/Hosts-for-Surge/issues/2#issuecomment-209851177>
>
-- 
能蟹仔

**Comment by ifyour** [comment]
@androidcn 最新的TestFlight未做过测试，不过按照规则文件的语法，这些都是通用的。😐 试试重启设备。
