### ISSUE TITLE
youtube可以打开但视频看不了！

### ISSUE THREAD

**Issue by sujianchao** [ifyour/Hosts-for-Surge#4]
如题
我用[https://github.com/cnAnonymous/hosts](https://github.com/cnAnonymous/hosts)这个hosts 替换系统hosts 后youtube等都一切正常，可否参考这文件更新下。

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube,还可以看很多海外禁网新闻，速度不错
