### ISSUE TITLE
建议增加几条规则

### ISSUE THREAD

**Issue by alexhua** [ifyour/Hosts-for-Surge#8]
```
#!MANAGED-CONFIG
https://raw.githubusercontent.com/ifyour/Hosts-for-Surge/master/hosts.conf interval=86400
```

Surge 现在支持远程自动更新config了 86400表示间隔24小时更新一次

`dns-server = 8.8.4.4, 8.8.8.8, 114.114.114.114`

dns 可以多设置几个

```
[URL Rewrite]
^http://www.google.cn https://www.google.com 302
```

这条规则可以让safari使用google作为默认搜索引擎了 可以直接在地址栏和spotlight里搜索关键字

另外facebook貌似不好用了，能否更新一下。

**Comment by yeafel** [comment]
直接发PR
